# Generated by Django 6.0.7 on 2026-07-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0004_remove_billing_product_mapping_billing_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='unit',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255, unique=True)),
                ('print_label', models.CharField(max_length=255)),
            ],
        ),
    ]
