# Generated by Django 6.0.7 on 2026-07-22 18:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0007_alter_product_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='hybrid_billing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phonenumber', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('grandtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentmode', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.user')),
            ],
        ),
        migrations.CreateModel(
            name='hybrid_billing_product_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.hybrid_billing')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
        ),
    ]
