# Generated by Django 6.0.7 on 2026-07-22 18:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0008_hybrid_billing_hybrid_billing_product_mapping'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hybrid_billing_product_mapping',
            name='billing_id',
        ),
        migrations.RemoveField(
            model_name='hybrid_billing_product_mapping',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='retail_billing',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='retail_billing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='retail_billing_product_mapping',
            name='billing_id',
        ),
        migrations.RemoveField(
            model_name='retail_billing_product_mapping',
            name='product_id',
        ),
        migrations.RemoveField(
            model_name='wholesale_billing',
            name='customer',
        ),
        migrations.RemoveField(
            model_name='wholesale_billing',
            name='user',
        ),
        migrations.RemoveField(
            model_name='wholesale_billing_product_mapping',
            name='billing_id',
        ),
        migrations.RemoveField(
            model_name='wholesale_billing_product_mapping',
            name='product_id',
        ),
        migrations.CreateModel(
            name='billing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, db_index=True, max_length=255, null=True, unique=True)),
                ('phonenumber', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('grandtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentmode', models.CharField(max_length=255)),
                ('bill_type', models.IntegerField(db_index=True, default=1)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.user')),
            ],
            options={
                'ordering': ['-datetime'],
            },
        ),
        migrations.CreateModel(
            name='billing_product_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_mapping', to='billing.billing')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
        ),
        migrations.DeleteModel(
            name='hybrid_billing',
        ),
        migrations.DeleteModel(
            name='hybrid_billing_product_mapping',
        ),
        migrations.DeleteModel(
            name='retail_billing',
        ),
        migrations.DeleteModel(
            name='retail_billing_product_mapping',
        ),
        migrations.DeleteModel(
            name='wholesale_billing',
        ),
        migrations.DeleteModel(
            name='wholesale_billing_product_mapping',
        ),
    ]
