# Generated by Django 6.0.7 on 2026-07-20 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_customer_expense_product_remove_user_username_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchaseprice',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
