# Generated by Django 6.0.7 on 2026-07-21 07:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0003_product_purchaseprice'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billing_product_mapping',
            name='billing_id',
        ),
        migrations.RemoveField(
            model_name='billing_product_mapping',
            name='product_id',
        ),
        migrations.AddField(
            model_name='expense',
            name='photourl',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.CreateModel(
            name='retail_billing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phonenumber', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('grandtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentmode', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.user')),
            ],
        ),
        migrations.CreateModel(
            name='retail_billing_product_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.retail_billing')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
        ),
        migrations.CreateModel(
            name='wholesale_billing',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('bill_number', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('phonenumber', models.CharField(max_length=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('grandtotal', models.DecimalField(decimal_places=2, max_digits=10)),
                ('paymentmode', models.CharField(max_length=255)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.customer')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.user')),
            ],
        ),
        migrations.CreateModel(
            name='wholesale_billing_product_mapping',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('line_total', models.DecimalField(decimal_places=2, max_digits=10)),
                ('billing_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.wholesale_billing')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='billing.product')),
            ],
        ),
        migrations.DeleteModel(
            name='billing',
        ),
        migrations.DeleteModel(
            name='billing_product_mapping',
        ),
    ]
