# Generated by Django 6.0.7 on 2026-07-21 13:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0005_unit'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['id']},
        ),
    ]
